

var units = new Array();
units.push(new unitclass("Amphibious Tank", 2, 10, 2));
units.push(new unitclass("Amtrac", 2, 70, 30));
units.push(new unitclass("Anti-Air", 1, 0, 0.6));
units.push(new unitclass("Anti-Tank", 1, 0, 0.6));
units.push(new unitclass("Armored Car", 2, 10, 2));
units.push(new unitclass("Artillery", 3, 0, 0.6));
units.push(new unitclass("Bicycle", 2, 60, 25));
units.push(new unitclass("Calvary", 2, 70, 25));
units.push(new unitclass("Heavy SP Anti-Air", 1, 0, 0.6));
units.push(new unitclass("Heavy SP Artillery", 3, 0, 0.6));
units.push(new unitclass("Heavy Tank", 2, 10, 2));
units.push(new unitclass("Heavy Tank Destroyer", 2, 0, 0.6));
units.push(new unitclass("Infantry", 2, 60, 25));
units.push(new unitclass("Light SP Anti-Air", 1, 0, 0.6));
units.push(new unitclass("Light SP Artillery", 3, 0, 0.6));
units.push(new unitclass("Light Tank", 2, 10, 2));
units.push(new unitclass("Light Tank Destroyer", 2, 0, 0.6));
units.push(new unitclass("Marines", 2, 70, 20));
units.push(new unitclass("Mechanized", 2, 60, 30));
units.push(new unitclass("Medium SP Anti-Air", 1, 0, 0.6));
units.push(new unitclass("Medium SP Artillery", 3, 0, 0.6));
units.push(new unitclass("Medium Tank", 2, 10, 2));
units.push(new unitclass("Medium Tank Destroyer", 2, 0, 0.6));
units.push(new unitclass("Modern SP Anti-Air", 1, 0, 0.6));
units.push(new unitclass("Modern SP Artillery", 3, 0, 0.6));
units.push(new unitclass("Modern Tank", 2, 10, 2));
units.push(new unitclass("Modern Tank Destroyer", 2, 0, 0.6));
units.push(new unitclass("Motorized", 2, 60, 25));
units.push(new unitclass("Motorized Anti-Air", 1, 0, 0.6));
units.push(new unitclass("Motorized Anti-Tank", 2, 0, 0.6));
units.push(new unitclass("Motorized Artillery", 3, 0, 0.6));
units.push(new unitclass("Motorized Rocket Artillery", 3, 0, 0.6));
units.push(new unitclass("Mountain", 2, 70, 20));
units.push(new unitclass("Paratrooper", 2, 70, 22));
units.push(new unitclass("Rocket Artillery", 3, 0, 0.6));
units.push(new unitclass("Super-Heavy SP Anti-Air", 1, 0, 0.6));
units.push(new unitclass("Super-Heavy SP Artillery", 3, 0, 0.6));
units.push(new unitclass("Super-Heavy Tank", 2, 0, 0.6));
units.push(new unitclass("Super-Heavy Tank Destroyer", 2, 10, 2));
