

var units = new Array();
units.push(new unitclass("Amphibious Tank", "Amphibious Tank I", 2, 10, 2));
units.push(new unitclass("Amtrac", "Basic Amtrac", 2, 70, 30));
units.push(new unitclass("Anti-Air", "Anti-Air I", 1, 0, 0.6));
units.push(new unitclass("Anti-Tank", "Anti-Tank I", 1, 0, 0.6));
units.push(new unitclass("Armored Car", "Interwar Armored Car", 2, 10, 2));
units.push(new unitclass("Artillery", "Artillery I", 3, 0, 0.6));
units.push(new unitclass("Bicycle", "Basic Infantry Equipment", 2, 60, 25));
units.push(new unitclass("Calvary", "Basic Infantry Equipment", 2, 70, 25));
units.push(new unitclass("Heavy SP Anti-Air", "Heavy Tank I", 1, 0, 0.6));
units.push(new unitclass("Heavy SP Artillery", "Heavy Tank I", 3, 0, 0.6));
units.push(new unitclass("Heavy Tank", "Heavy Tank I", 2, 10, 2));
units.push(new unitclass("Heavy Tank Destroyer", "Heavy Tank I", 2, 0, 0.6));
units.push(new unitclass("Infantry", "Basic Infantry Equipment", 2, 60, 25));
units.push(new unitclass("Light SP Anti-Air", "Light Tank I", 1, 0, 0.6));
units.push(new unitclass("Light SP Artillery", "Light Tank I", 3, 0, 0.6));
units.push(new unitclass("Light Tank", "Great War Tank", 2, 10, 2));
units.push(new unitclass("Light Tank Destroyer", "Light Tank I", 2, 0, 0.6));
units.push(new unitclass("Marines", "Marines I", 2, 70, 20));
units.push(new unitclass("Mechanized", "Mechanized I", 2, 60, 30));
units.push(new unitclass("Medium SP Anti-Air", "Medium Tank I",1, 0, 0.6));
units.push(new unitclass("Medium SP Artillery", "Medium Tank I",3, 0, 0.6));
units.push(new unitclass("Medium Tank", "Medium Tank I",2, 10, 2));
units.push(new unitclass("Medium Tank Destroyer", "Medium Tank I",2, 0, 0.6));
units.push(new unitclass("Modern SP Anti-Air", "Modern Tank", 1, 0, 0.6));
units.push(new unitclass("Modern SP Artillery", "Modern Tank",3, 0, 0.6));
units.push(new unitclass("Modern Tank", "Modern Tank",2, 10, 2));
units.push(new unitclass("Modern Tank Destroyer", "Modern Tank",2, 0, 0.6));
units.push(new unitclass("Motorized", "Motorized",2, 60, 25));
units.push(new unitclass("Motorized Anti-Air", "Anti-Air I",1, 0, 0.6));
units.push(new unitclass("Motorized Anti-Tank", "Anti-Tank I",2, 0, 0.6));
units.push(new unitclass("Motorized Artillery", "Artillery I",3, 0, 0.6));
units.push(new unitclass("Motorized Rocket Artillery", "Rocket Artillery", 3, 0, 0.6));
units.push(new unitclass("Mountain", "Mountain Infantry I", 2, 70, 20));
units.push(new unitclass("Paratrooper", "Paratroopers I", 2, 70, 22));
units.push(new unitclass("Rocket Artillery", "Rocket Artillery", 3, 0, 0.6));
units.push(new unitclass("Super-Heavy SP Anti-Air", "Super-Heavy Tank",1, 0, 0.6));
units.push(new unitclass("Super-Heavy SP Artillery", "Super-Heavy Tank",3, 0, 0.6));
units.push(new unitclass("Super-Heavy Tank", "Super-Heavy Tank",2, 0, 0.6));
units.push(new unitclass("Super-Heavy Tank Destroyer", "Super-Heavy Tank",2, 10, 2));
